apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: petclinic-build-stage
spec:
  pipelineRef:
    name: petclinic-build-stage
  workspaces:
  - name: workspace
    persistentVolumeClaim:
      claimName: petclinic-build-workspace
  - name: maven-settings
    configMap:
      name: maven-settings
